### ISSUE TITLE
Test with special chars in search-query

### ISSUE THREAD

**Issue by tijsverkoyen** [sumocoders/FrameworkSearchBundle#2]

**Comment by WouterSioen** [comment]
Tested with all characters/words/sentences from https://github.com/minimaxir/big-list-of-naughty-strings

None of these gives problems, so this means the search is secure and no injection of any type can be done.

Searching for emoji style characters does not work though, because our database tables are in the utf8 character set and not in the utf8mb4 character set. This doesn't seem a problem to me though. I don't think we'll ever want to search on emoji?

**Comment by tijsverkoyen** [comment]
Wouldn't it be more future-proof to use utf8mb4? As our clients will use emoji's as they are hip(ster)

**Comment by WouterSioen** [comment]
If we do this, I'd make **all** database tables utf8mb4. Having different encodings slows down joins and is harder to set up when connecting to your database.

**Comment by tijsverkoyen** [comment]
uhu, I think this will be more future proof.

**Comment by WouterSioen** [comment]
Ok, I'll close this issue and create a new issue for the utf8mb4 stuff (on the framework repo)
